[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "app"
version = "0.1.0"
packages = [
    { include = "app", from = "." }
]

[tool.poetry.dependencies]
python = "^3.8"
dependency_injector = "^4.45.0"
SQLAlchemy = "^2.0.37"

[tool.poetry.group.lint.dependencies]
mypy = "1.10.0"
importanize = "0.7.0"
ruff = "0.4.8"


[tool.pytest.ini_options]
asyncio_mode = "auto"